name: Automated Deployment to Staging Environment

on: 
  workflow_dispatch:
  
  push:
    branches:
      - testing

env:
  AZURE_CLUSTER_NAME: week10-aks-cluster
  RESOURCE_GROUP: week10-rg-staging
  STAGING_STORAGE_NAME: week10storagestaging
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  LOCATION: eastus

jobs:
  test_and_push_backend:
    uses: ./.github/workflows/backend_ci.yml
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  test_and_push_frontend:
    uses: ./.github/workflows/frontend_ci.yml
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  create_staging_environment:
    needs: 
      - test_and_push_backend
      - test_and_push_frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Kubernetes context (get AKS credentials)
      run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AZURE_CLUSTER_NAME }} --overwrite-existing
    
    - name: Create Staging Namespace
      run: |
        kubectl delete namespace staging --ignore-not-found
        kubectl wait --for=delete namespace/staging --timeout=120s || true
        kubectl create namespace staging
    
    - name: Create Azure Storage Account
      run: |
        az storage account create \
          --name ${{ env.STAGING_STORAGE_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --location ${{ env.LOCATION }} \
          --sku Standard_LRS

    - name: Logout from Azure
      run: az logout
  
  deploy_backend:
    needs:
      - create_staging_environment
    uses: ./.github/workflows/backend_cd.yml
    with:
      aks_cluster_name: 'week10-aks-cluster'
      aks_resource_group: 'week10-rg-staging'
      aks_acr_name: 'danuthacr'
      aks_storage_name: 'week10storagestaging'
      aks_namespace: 'staging'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  deploy_frontend:
    needs: deploy_backend
    uses: ./.github/workflows/frontend_cd.yml
    with:
      product_api_ip: ${{ needs.deploy_backend.outputs.PRODUCT_API_IP }}
      order_api_ip: ${{ needs.deploy_backend.outputs.ORDER_API_IP }}
      customer_api_ip: ${{ needs.deploy_backend.outputs.CUSTOMER_API_IP }}
      aks_cluster_name: 'week10-aks-cluster'
      aks_resource_group: 'week10-rg-staging'
      aks_namespace: 'staging'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  


       